### ISSUE TITLE
put pg* in an array

### ISSUE THREAD

**Issue by chtzvt** [AzuraDev/keyboardChrome#3]
For every unnecessary variable in your script, a fuzzy woodland animal is massacred.

Save the fuzzy animals, clean up your variables.

**Comment by AzuraDev** [comment]
Keep in mind My Keychrome thing is my first js thing i made its un neat ill clean it up thanks for the heads up

**Comment by AzuraDev** [comment]
And i dont need to i just like the way it looks, theres nothing wrong with it

**Comment by chtzvt** [comment]
No problem, just giving suggestions.

**Comment by AzuraDev** [comment]
Oh no i didnt mean it like that XD thanks for your sugestions
